/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assessments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List saved assessments for this device */
        get: operations["list_assessments_api_v1_assessments_get"];
        put?: never;
        /** Generate an assessment */
        post: operations["create_assessment_api_v1_assessments_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate an assessment, streaming per-step progress (Server-Sent Events) */
        post: operations["stream_assessment_api_v1_assessments_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{assessment_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Assessment */
        get: operations["get_assessment_api_v1_assessments__assessment_id__get"];
        put?: never;
        post?: never;
        /** Delete Assessment */
        delete: operations["delete_assessment_api_v1_assessments__assessment_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{assessment_id}/export.{fmt}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Export as PDF, iCalendar (.ics) or JSON */
        get: operations["export_api_v1_assessments__assessment_id__export__fmt__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{assessment_id}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Logs */
        get: operations["list_logs_api_v1_assessments__assessment_id__logs_get"];
        put?: never;
        /** Add Log */
        post: operations["add_log_api_v1_assessments__assessment_id__logs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{assessment_id}/logs/{log_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete Log */
        delete: operations["delete_log_api_v1_assessments__assessment_id__logs__log_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{assessment_id}/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Progress */
        get: operations["get_progress_api_v1_assessments__assessment_id__progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{assessment_id}/replan": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Regenerate the next training block using logged progress */
        post: operations["replan_api_v1_assessments__assessment_id__replan_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assessments/{assessment_id}/replan/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Replan, streaming progress (SSE) */
        post: operations["replan_stream_api_v1_assessments__assessment_id__replan_stream_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Accuracy, per-class metrics and confusion matrices on the evaluation CSVs */
        get: operations["models_evaluation_api_v1_models_evaluation_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/models/info": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Model metadata, training-data provenance and limitations */
        get: operations["models_info_api_v1_models_info_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/workflow": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** The pipeline steps, in order */
        get: operations["workflow_api_v1_workflow_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Assessment */
        Assessment: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /**
             * Errors
             * @default []
             */
            errors: components["schemas"]["NodeError"][];
            fitness?: components["schemas"]["FitnessResult"] | null;
            /** Id */
            id: string;
            injury?: components["schemas"]["InjuryResult"] | null;
            metrics?: components["schemas"]["Metrics"] | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "mock" | "live";
            normalized?: components["schemas"]["NormalizedInputs"] | null;
            nutrition?: components["schemas"]["NutritionPlan"] | null;
            /** Parent Id */
            parent_id?: string | null;
            profile: components["schemas"]["ProfileIn"];
            progress_context?: components["schemas"]["ProgressContext"] | null;
            recovery?: components["schemas"]["RecoveryPlan"] | null;
            safety?: components["schemas"]["SafetyResult"] | null;
            /**
             * Sections
             * @default {}
             */
            sections: {
                [key: string]: "ok" | "partial" | "failed" | "skipped";
            };
            /**
             * Simulated
             * @description True when produced by the mock generator rather than a live model
             */
            simulated: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "partial" | "failed";
            /**
             * Warnings
             * @default []
             */
            warnings: string[];
            workout?: components["schemas"]["WorkoutPlan"] | null;
        };
        /** AssessmentRequest */
        AssessmentRequest: {
            /**
             * Mode
             * @default mock
             * @enum {string}
             */
            mode: "mock" | "live";
            profile: components["schemas"]["ProfileIn"];
        };
        /** AssessmentSummary */
        AssessmentSummary: {
            /**
             * Created At
             * Format: date-time
             */
            created_at: string;
            /** Daily Calorie Target */
            daily_calorie_target: number | null;
            /** Fitness Goal */
            fitness_goal: string;
            /** Fitness Level */
            fitness_level: string | null;
            /** Id */
            id: string;
            /** Injury Risk */
            injury_risk: string | null;
            /**
             * Mode
             * @enum {string}
             */
            mode: "mock" | "live";
            /** Parent Id */
            parent_id: string | null;
            /** Safety Level */
            safety_level: string | null;
            /** Sessions Per Week */
            sessions_per_week: number | null;
            /** Simulated */
            simulated: boolean;
            /**
             * Status
             * @enum {string}
             */
            status: "complete" | "partial" | "failed";
            /** User Name */
            user_name: string | null;
        };
        /** Driver */
        Driver: {
            /**
             * Effect Pct Points
             * @description Change in the predicted class's probability vs a baseline profile
             */
            effect_pct_points: number;
            /** Feature */
            feature: string;
            /** Value */
            value: unknown;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /**
             * Field Errors
             * @default []
             */
            field_errors: components["schemas"]["FieldError"][];
            /** Message */
            message: string;
            /** Request Id */
            request_id?: string | null;
        };
        /** ErrorResponse */
        ErrorResponse: {
            error: components["schemas"]["ErrorBody"];
        };
        /** Exercise */
        Exercise: {
            /** Exercise Name */
            exercise_name: string;
            /** Notes */
            notes?: string | null;
            /** Reps */
            reps: string;
            /**
             * Rest Period
             * @default 60 sec
             */
            rest_period: string;
            /** Sets */
            sets: number;
        };
        /** FieldError */
        FieldError: {
            /** Field */
            field: string;
            /** Message */
            message: string;
        };
        /** FitnessResult */
        FitnessResult: {
            /**
             * Confidence
             * @description Probability of the predicted class, in percent (0-100).
             */
            confidence: number;
            /**
             * Drivers
             * @default []
             */
            drivers: components["schemas"]["Driver"][];
            /** Level */
            level: string;
            /**
             * Notes
             * @default []
             */
            notes: string[];
            /**
             * Probabilities
             * @description Probability of each class as a fraction (0-1); they sum to 1.
             */
            probabilities: {
                [key: string]: number;
            };
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /** Database */
            database: boolean;
            /** Models Loaded */
            models_loaded: boolean;
            /** Status */
            status: string;
            /** Version */
            version: string;
        };
        /** InjuryResult */
        InjuryResult: {
            /**
             * Confidence
             * @description Probability of the predicted class, in percent (0-100).
             */
            confidence: number;
            /**
             * Drivers
             * @default []
             */
            drivers: components["schemas"]["Driver"][];
            /**
             * Notes
             * @default []
             */
            notes: string[];
            /**
             * Probabilities
             * @description Probability of each class as a fraction (0-1); they sum to 1.
             */
            probabilities: {
                [key: string]: number;
            };
            /** Risk */
            risk: string;
            /**
             * Risk Factors
             * @default []
             */
            risk_factors: string[];
        };
        /** MacroTargets */
        MacroTargets: {
            /** Carbs G */
            carbs_g: number;
            /** Fat G */
            fat_g: number;
            /** Protein G */
            protein_g: number;
        };
        /** Meal */
        Meal: {
            /** Calories */
            calories: number;
            /** Carbs G */
            carbs_g: number;
            /** Fat G */
            fat_g: number;
            /** Foods */
            foods: string[];
            /** Meal Name */
            meal_name: string;
            /** Protein G */
            protein_g: number;
        };
        /** Metrics */
        Metrics: {
            /** Age Category */
            age_category: string;
            /** Bmi */
            bmi: number;
            /** Bmi Category */
            bmi_category: string;
        };
        /** NodeError */
        NodeError: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Node */
            node: string;
            /**
             * Retryable
             * @default false
             */
            retryable: boolean;
        };
        /** NormalizedExperience */
        NormalizedExperience: {
            /**
             * Activity Description
             * @default
             */
            activity_description: string;
            /**
             * Experience Level
             * @enum {string}
             */
            experience_level: "Never Exercised" | "Beginner" | "Some Experience" | "Advanced";
            /** Years Active */
            years_active: number;
        };
        /** NormalizedHealth */
        NormalizedHealth: {
            /**
             * Cleared For Exercise
             * @default true
             */
            cleared_for_exercise: boolean;
            /** Conditions */
            conditions?: string[];
            /** Exercise Limitations */
            exercise_limitations?: string[];
            /**
             * Severity Assessment
             * @default none
             * @enum {string}
             */
            severity_assessment: "none" | "mild" | "moderate" | "severe";
        };
        /** NormalizedInputs */
        NormalizedInputs: {
            experience: components["schemas"]["NormalizedExperience"];
            health: components["schemas"]["NormalizedHealth"];
            schedule: components["schemas"]["NormalizedSchedule"];
        };
        /** NormalizedSchedule */
        NormalizedSchedule: {
            /** Estimated Hours Per Week */
            estimated_hours_per_week: number;
            /** Preferred Days */
            preferred_days?: ("Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday")[];
            /** Preferred Times */
            preferred_times?: string[];
            /** Schedule Constraints */
            schedule_constraints?: string[];
        };
        /** NutritionPlan */
        NutritionPlan: {
            /** Daily Calorie Target */
            daily_calorie_target: number;
            /**
             * Hydration Recommendation
             * @default
             */
            hydration_recommendation: string;
            macro_targets: components["schemas"]["MacroTargets"];
            /** Maintenance Calories */
            maintenance_calories: number;
            /** Meal Suggestions */
            meal_suggestions?: components["schemas"]["Meal"][];
            /** Meal Totals */
            meal_totals?: {
                [key: string]: number;
            };
            /** Notes */
            notes?: string[];
            /**
             * Nutrition Timing Guidance
             * @default
             */
            nutrition_timing_guidance: string;
        };
        /**
         * ProfileIn
         * @description User profile as submitted by the frontend. Free-text fields are length-limited and sanitised.
         */
        ProfileIn: {
            /** Age */
            age: number;
            /**
             * Available Hours Per Week
             * @description Free text, e.g. '4-5 hours, weekday mornings'
             */
            available_hours_per_week: string;
            /**
             * Fitness Experience
             * @description Free text, e.g. '2 years of gym training'
             */
            fitness_experience: string;
            /**
             * Fitness Goal
             * @enum {string}
             */
            fitness_goal: "Weight Loss" | "Muscle Building" | "Endurance/Cardio" | "General Fitness";
            /**
             * Gender
             * @enum {string}
             */
            gender: "Male" | "Female" | "Other";
            /**
             * Health Conditions
             * @default None
             */
            health_conditions: string;
            /** Height Cm */
            height_cm: number;
            /**
             * Previous Injury
             * @default false
             */
            previous_injury: boolean;
            /** User Name */
            user_name?: string | null;
            /** Weight Kg */
            weight_kg: number;
        };
        /** ProgressContext */
        ProgressContext: {
            /** Adherence Pct */
            adherence_pct?: number | null;
            /** Average Rpe */
            average_rpe?: number | null;
            /**
             * Deload Due
             * @default false
             */
            deload_due: boolean;
            /** Latest Weight Kg */
            latest_weight_kg?: number | null;
            /**
             * Notes
             * @default []
             */
            notes: string[];
            /**
             * Planned Sessions Per Week
             * @default 0
             */
            planned_sessions_per_week: number;
            /**
             * Sessions Last 28 Days
             * @default 0
             */
            sessions_last_28_days: number;
            /**
             * Weeks On Plan
             * @default 0
             */
            weeks_on_plan: number;
            /** Weight Change Kg */
            weight_change_kg?: number | null;
        };
        /** ProgressLogIn */
        ProgressLogIn: {
            /**
             * Completed
             * @default true
             */
            completed: boolean;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /**
             * Kind
             * @enum {string}
             */
            kind: "session" | "weight";
            /**
             * Logged On
             * Format: date
             */
            logged_on?: string;
            /** Notes */
            notes?: string | null;
            /** Planned Day */
            planned_day?: string | null;
            /**
             * Rpe
             * @description Rate of perceived exertion, 1-10
             */
            rpe?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
        };
        /** ProgressLogOut */
        ProgressLogOut: {
            /** Assessment Id */
            assessment_id: string;
            /**
             * Completed
             * @default true
             */
            completed: boolean;
            /** Duration Minutes */
            duration_minutes?: number | null;
            /** Id */
            id: number;
            /**
             * Kind
             * @enum {string}
             */
            kind: "session" | "weight";
            /**
             * Logged On
             * Format: date
             */
            logged_on?: string;
            /** Notes */
            notes?: string | null;
            /** Planned Day */
            planned_day?: string | null;
            /**
             * Rpe
             * @description Rate of perceived exertion, 1-10
             */
            rpe?: number | null;
            /** Weight Kg */
            weight_kg?: number | null;
        };
        /** ProgressSummary */
        ProgressSummary: {
            /** Adherence Pct */
            adherence_pct: number | null;
            /** Assessment Id */
            assessment_id: string;
            /** Average Rpe */
            average_rpe: number | null;
            /** Deload Due */
            deload_due: boolean;
            /** Latest Weight Kg */
            latest_weight_kg: number | null;
            /** Notes */
            notes: string[];
            /** Planned Sessions Per Week */
            planned_sessions_per_week: number;
            /** Sessions Last 28 Days */
            sessions_last_28_days: number;
            /** Weekly */
            weekly: components["schemas"]["WeekAdherence"][];
            /** Weeks On Plan */
            weeks_on_plan: number;
            /** Weight Change Kg */
            weight_change_kg: number | null;
            /** Weights */
            weights: [
                string,
                number
            ][];
        };
        /** RecoveryPlan */
        RecoveryPlan: {
            /** Adherence Tips */
            adherence_tips?: string[];
            /**
             * Deload Strategy
             * @default
             */
            deload_strategy: string;
            /** Habit Formation Strategies */
            habit_formation_strategies?: string[];
            /** Mobility Work */
            mobility_work?: string[];
            /** Recovery Techniques */
            recovery_techniques?: string[];
            /** Rest Day Activities */
            rest_day_activities?: string[];
            schedule_integration: components["schemas"]["ScheduleIntegration"];
            sleep_recommendations: components["schemas"]["SleepRecommendations"];
            /** Stress Management Techniques */
            stress_management_techniques?: string[];
            /** Time Management Tips */
            time_management_tips?: string[];
        };
        /** ReplanRequest */
        ReplanRequest: {
            /**
             * Mode
             * @default mock
             * @enum {string}
             */
            mode: "mock" | "live";
        };
        /** SafetyResult */
        SafetyResult: {
            /**
             * Constraints
             * @default []
             */
            constraints: string[];
            /** Disclaimer */
            disclaimer: string;
            /**
             * Level
             * @enum {string}
             */
            level: "standard" | "conservative" | "clinician_first";
            /** Max Intensity */
            max_intensity: string;
            /** Max Sessions Per Week */
            max_sessions_per_week: number;
            /**
             * Reasons
             * @default []
             */
            reasons: string[];
            /** Requires Clearance */
            requires_clearance: boolean;
        };
        /** ScheduleIntegration */
        ScheduleIntegration: {
            /** Best Days */
            best_days?: string[];
            /** Best Times */
            best_times?: string[];
            /**
             * Weekly Schedule Tips
             * @default
             */
            weekly_schedule_tips: string;
        };
        /** SleepRecommendations */
        SleepRecommendations: {
            /** Hours Per Night */
            hours_per_night: number;
            /** Sleep Quality Tips */
            sleep_quality_tips?: string[];
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** WeekAdherence */
        WeekAdherence: {
            /** Planned */
            planned: number;
            /** Sessions */
            sessions: number;
            /**
             * Week Start
             * Format: date
             */
            week_start: string;
        };
        /** WorkoutDay */
        WorkoutDay: {
            /**
             * Day
             * @enum {string}
             */
            day: "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday";
            /** Exercises */
            exercises: components["schemas"]["Exercise"][];
            /**
             * Focus
             * @default
             */
            focus: string;
        };
        /** WorkoutPlan */
        WorkoutPlan: {
            /** Weekly Schedule */
            weekly_schedule: components["schemas"]["WorkoutDay"][];
            /** Workout Duration Per Session */
            workout_duration_per_session: number;
            /** Workout Equipment Needed */
            workout_equipment_needed?: string[];
            /** Workout Frequency Per Week */
            workout_frequency_per_week: number;
            /**
             * Workout Intensity Level
             * @enum {string}
             */
            workout_intensity_level: "Light" | "Moderate" | "Vigorous";
            /**
             * Workout Progression Timeline
             * @default
             */
            workout_progression_timeline: string;
            /** Workout Safety Notes */
            workout_safety_notes?: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    list_assessments_api_v1_assessments_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous, client-generated identifier that scopes saved plans to one browser. */
                "x-device-id"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssessmentSummary"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_assessment_api_v1_assessments_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous, client-generated identifier that scopes saved plans to one browser. */
                "x-device-id"?: string | null;
                /** @description Bring-your-own Gemini API key. Used for this request only; never stored or logged. */
                "x-gemini-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid or missing Gemini API key (live mode) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited (this API or the Gemini key's quota) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    stream_assessment_api_v1_assessments_stream_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous, client-generated identifier that scopes saved plans to one browser. */
                "x-device-id"?: string | null;
                /** @description Bring-your-own Gemini API key. Used for this request only; never stored or logged. */
                "x-gemini-api-key"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AssessmentRequest"];
            };
        };
        responses: {
            /** @description SSE events: start, node, result, error */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "text/event-stream": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid or missing Gemini API key (live mode) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited (this API or the Gemini key's quota) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_assessment_api_v1_assessments__assessment_id__get: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous, client-generated identifier that scopes saved plans to one browser. */
                "x-device-id"?: string | null;
            };
            path: {
                /** @description Assessment UUID */
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid or missing Gemini API key (live mode) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited (this API or the Gemini key's quota) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_assessment_api_v1_assessments__assessment_id__delete: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous, client-generated identifier that scopes saved plans to one browser. */
                "x-device-id"?: string | null;
            };
            path: {
                /** @description Assessment UUID */
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid or missing Gemini API key (live mode) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited (this API or the Gemini key's quota) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    export_api_v1_assessments__assessment_id__export__fmt__get: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous, client-generated identifier that scopes saved plans to one browser. */
                "x-device-id"?: string | null;
            };
            path: {
                /** @description Assessment UUID */
                assessment_id: string;
                fmt: "pdf" | "ics" | "json";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                    "application/pdf": unknown;
                    "text/calendar": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid or missing Gemini API key (live mode) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited (this API or the Gemini key's quota) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    list_logs_api_v1_assessments__assessment_id__logs_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous, client-generated identifier that scopes saved plans to one browser. */
                "x-device-id"?: string | null;
            };
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressLogOut"][];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    add_log_api_v1_assessments__assessment_id__logs_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous, client-generated identifier that scopes saved plans to one browser. */
                "x-device-id"?: string | null;
            };
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProgressLogIn"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressLogOut"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    delete_log_api_v1_assessments__assessment_id__logs__log_id__delete: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous, client-generated identifier that scopes saved plans to one browser. */
                "x-device-id"?: string | null;
            };
            path: {
                assessment_id: string;
                log_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_progress_api_v1_assessments__assessment_id__progress_get: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous, client-generated identifier that scopes saved plans to one browser. */
                "x-device-id"?: string | null;
            };
            path: {
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProgressSummary"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    replan_api_v1_assessments__assessment_id__replan_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous, client-generated identifier that scopes saved plans to one browser. */
                "x-device-id"?: string | null;
                /** @description Bring-your-own Gemini API key. Used for this request only; never stored or logged. */
                "x-gemini-api-key"?: string | null;
            };
            path: {
                /** @description Assessment UUID */
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Assessment"];
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid or missing Gemini API key (live mode) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited (this API or the Gemini key's quota) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    replan_stream_api_v1_assessments__assessment_id__replan_stream_post: {
        parameters: {
            query?: never;
            header?: {
                /** @description Anonymous, client-generated identifier that scopes saved plans to one browser. */
                "x-device-id"?: string | null;
                /** @description Bring-your-own Gemini API key. Used for this request only; never stored or logged. */
                "x-gemini-api-key"?: string | null;
            };
            path: {
                /** @description Assessment UUID */
                assessment_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReplanRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Bad Request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Invalid or missing Gemini API key (live mode) */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Unprocessable Entity */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited (this API or the Gemini key's quota) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Service Unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    models_evaluation_api_v1_models_evaluation_get: {
        parameters: {
            query?: {
                refresh?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    models_info_api_v1_models_info_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
    workflow_api_v1_workflow_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
        };
    };
}
