import { useState } from "react";
import { Link, useNavigate } from "react-router-dom";
import { ApiError, streamCreate } from "../api/client";
import type { ProfileIn } from "../api/types";
import { ErrorNotice, Notice } from "../components/Notice";
import { ProfileForm } from "../components/ProfileForm";
import { ProgressSteps } from "../components/ProgressSteps";
import { useGeneration } from "../lib/useGeneration";
import { serverFieldErrors } from "../lib/validation";
import { useSettings } from "../state/settings";

export function AssessPage() {
  const { mode, liveReady } = useSettings();
  const navigate = useNavigate();
  const gen = useGeneration();
  const [pending, setPending] = useState<ProfileIn | null>(null);
  const blocked = mode === "live" && !liveReady;

  const submit = async (profile: ProfileIn) => {
    setPending(profile);
    const result = await gen.run((onEvent, signal) => streamCreate(profile, mode, onEvent, signal));
    if (result) navigate(`/plans/${result.id}`);
  };

  const fieldErrors = gen.error instanceof ApiError ? serverFieldErrors(gen.error.fieldErrors) : undefined;

  return (
    <div className="stack">
      <div>
        <h1>Build your personalised plan</h1>
        <p className="lead">
          Tell us about yourself and get a fitness assessment, injury-risk estimate, weekly workout plan, nutrition targets and recovery guidance.
        </p>
      </div>

      {mode === "mock" ? (
        <Notice tone="info" title="Simulated mode">
          Workout, nutrition and recovery text is generated by built-in rules so you can try everything without an API key. The fitness and injury predictions always come from the trained models.{" "}
          <Link to="/settings">Use Gemini instead</Link>
        </Notice>
      ) : blocked ? (
        <Notice tone="warn" title="Add your Gemini API key" action={<Link className="btn btn-small" to="/settings">Open settings</Link>}>
          Live mode needs your own key. It stays in this browser tab and is sent only with your requests.
        </Notice>
      ) : null}

      {gen.error != null && <ErrorNotice error={gen.error} onRetry={pending ? () => submit(pending) : undefined} />}

      {gen.running && (
        <section className="card" aria-busy="true">
          <h2>Creating your plan…</h2>
          <ProgressSteps nodes={gen.nodes} state={gen.steps} />
          <button className="btn" onClick={gen.cancel}>
            Cancel
          </button>
        </section>
      )}
      {/* Kept mounted (just hidden) while generating so nothing the user typed is lost if it fails. */}
      <section className="card" hidden={gen.running}>
        <ProfileForm onSubmit={submit} disabled={blocked} serverErrors={fieldErrors} />
      </section>
    </div>
  );
}
