import type { Assessment } from "../api/types";

export function makeAssessment(over: Partial<Assessment> = {}): Assessment {
  return {
    id: "11111111-2222-3333-4444-555555555555",
    created_at: "2026-09-29T10:00:00Z",
    mode: "mock",
    simulated: true,
    status: "complete",
    parent_id: null,
    profile: {
      user_name: "Asha",
      age: 34,
      height_cm: 165,
      weight_kg: 68,
      gender: "Female",
      fitness_goal: "General Fitness",
      fitness_experience: "Jogged for 2 years",
      available_hours_per_week: "4 hours",
      health_conditions: "None",
      previous_injury: false,
    },
    metrics: { bmi: 25, bmi_category: "Overweight", age_category: "Adult" },
    normalized: {
      experience: { experience_level: "Some Experience", years_active: 2, activity_description: "jogging" },
      health: { conditions: [], exercise_limitations: [], severity_assessment: "none", cleared_for_exercise: true },
      schedule: { estimated_hours_per_week: 4, preferred_days: ["Monday"], preferred_times: [], schedule_constraints: [] },
    },
    fitness: {
      level: "Intermediate",
      confidence: 61.2,
      probabilities: { Beginner: 0.2, Intermediate: 0.612, Advanced: 0.15, Athlete: 0.038 },
      drivers: [{ feature: "Age", value: 34, effect_pct_points: 6.5 }],
      notes: [],
    },
    injury: {
      risk: "Moderate Risk",
      confidence: 52,
      probabilities: { "Low Risk": 0.3, "Moderate Risk": 0.52, "High Risk": 0.15, "Very High Risk": 0.03 },
      risk_factors: ["Returning after a break"],
      drivers: [],
      notes: [],
    },
    safety: {
      level: "standard",
      max_intensity: "Vigorous",
      max_sessions_per_week: 6,
      requires_clearance: false,
      reasons: [],
      constraints: [],
      disclaimer: "Educational only.",
    },
    workout: {
      workout_frequency_per_week: 2,
      workout_duration_per_session: 45,
      workout_intensity_level: "Moderate",
      workout_progression_timeline: "Add a set every two weeks.",
      workout_equipment_needed: ["Dumbbells"],
      workout_safety_notes: ["Warm up first."],
      weekly_schedule: [
        { day: "Monday", focus: "Full body", exercises: [{ exercise_name: "Goblet squat", sets: 3, reps: "10", rest_period: "60s", notes: null }] },
        { day: "Thursday", focus: "Cardio", exercises: [{ exercise_name: "Brisk walk", sets: 1, reps: "30 min", rest_period: "-", notes: null }] },
      ],
    },
    nutrition: {
      maintenance_calories: 2000,
      daily_calorie_target: 1800,
      macro_targets: { protein_g: 120, carbs_g: 250, fat_g: 60 },
      meal_suggestions: [{ meal_name: "Breakfast", calories: 500, protein_g: 30, carbs_g: 60, fat_g: 15, foods: ["Idli", "Sambar"] }],
      hydration_recommendation: "2.5 L water.",
      nutrition_timing_guidance: "Eat protein after training.",
      notes: [],
    },
    recovery: {
      sleep_recommendations: { hours_per_night: 8, sleep_quality_tips: ["Keep a routine"] },
      schedule_integration: { best_days: ["Monday"], best_times: ["Morning"], weekly_schedule_tips: "Keep it regular." },
      recovery_techniques: ["Stretching"],
      rest_day_activities: [],
      mobility_work: [],
      stress_management_techniques: [],
      habit_formation_strategies: [],
      adherence_tips: [],
      time_management_tips: [],
      deload_strategy: "Every 5th week.",
    },
    errors: [],
    warnings: [],
    sections: { profile: "ok", fitness: "ok" },
    progress_context: null,
    ...over,
  } as Assessment;
}
